---
#playbook to create new Openstack flavor
- name: create flavor
  os_nova_flavor:
    name: "{{ item.name }}"
    ram: "{{ item.ram }}"
    vcpus: "{{ item.vcpu }}"
    disk: "{{ item.disk }}"
  with_items: "{{ flavors }}"

