---
# group vars for apps

yum_packages:
  - httpd

tomcat_dir: /usr/share/tomcat/webapps/ROOT
tomcat_index_dir: 
  - /usr/share/tomcat/webapps/ROOT/index.html
  - /usr/share/tomcat/webapps/ansible/index.html

webserver_app: "tomcat"





